language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 0.7
  - nightly

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

# script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'using Pkg;
#              Pkg.clone(pwd(), "AdvancedHMC");
#              Pkg.build("AdvancedHMC");
#              Pkg.test("AdvancedHMC"; coverage=true)'

after_success:
  - julia -e 'using Pkg;
              cd(Pkg.dir("AdvancedHMC"));
              Pkg.add("Coverage");
              using Coverage;
              Coveralls.submit(process_folder())'
